// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKdLkLtCkX5bRIZVPp0zkTQrsEC-DGVtU',
    appId: '1:872102038610:web:3242cbc8996a5dbf1d238b',
    messagingSenderId: '872102038610',
    projectId: 'hospitalmanagement-ssgmce',
    authDomain: 'hospitalmanagement-ssgmce.firebaseapp.com',
    databaseURL: 'https://hospitalmanagement-ssgmce-default-rtdb.firebaseio.com',
    storageBucket: 'hospitalmanagement-ssgmce.appspot.com',
    measurementId: 'G-SHC99GRZP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22ERUziHvub0qwe3dIQHmW3iX8ai9AZM',
    appId: '1:872102038610:android:80ee7eaf910a18a91d238b',
    messagingSenderId: '872102038610',
    projectId: 'hospitalmanagement-ssgmce',
    databaseURL: 'https://hospitalmanagement-ssgmce-default-rtdb.firebaseio.com',
    storageBucket: 'hospitalmanagement-ssgmce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYiBKuUvLLfAfNlm3YufYRwbgwWkHHAL0',
    appId: '1:872102038610:ios:27eef1845f4174561d238b',
    messagingSenderId: '872102038610',
    projectId: 'hospitalmanagement-ssgmce',
    databaseURL: 'https://hospitalmanagement-ssgmce-default-rtdb.firebaseio.com',
    storageBucket: 'hospitalmanagement-ssgmce.appspot.com',
    iosClientId: '872102038610-r8rjo8g3g1n2s1e9ah7t5m9lp1fl7an8.apps.googleusercontent.com',
    iosBundleId: 'com.gauravchaudhari.flutterxfirebase.flutterXFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYiBKuUvLLfAfNlm3YufYRwbgwWkHHAL0',
    appId: '1:872102038610:ios:27eef1845f4174561d238b',
    messagingSenderId: '872102038610',
    projectId: 'hospitalmanagement-ssgmce',
    databaseURL: 'https://hospitalmanagement-ssgmce-default-rtdb.firebaseio.com',
    storageBucket: 'hospitalmanagement-ssgmce.appspot.com',
    iosClientId: '872102038610-r8rjo8g3g1n2s1e9ah7t5m9lp1fl7an8.apps.googleusercontent.com',
    iosBundleId: 'com.gauravchaudhari.flutterxfirebase.flutterXFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKdLkLtCkX5bRIZVPp0zkTQrsEC-DGVtU',
    appId: '1:872102038610:web:484c02d4dcb75e7d1d238b',
    messagingSenderId: '872102038610',
    projectId: 'hospitalmanagement-ssgmce',
    authDomain: 'hospitalmanagement-ssgmce.firebaseapp.com',
    databaseURL: 'https://hospitalmanagement-ssgmce-default-rtdb.firebaseio.com',
    storageBucket: 'hospitalmanagement-ssgmce.appspot.com',
    measurementId: 'G-JL1ERKR1Z0',
  );

}